[package]
name = "spin"
description = "Super Pinball System"
version = "2.0.0-alpha.2"
authors = ["Mike McGann"]
repository = "https://github.com/drop-target-pinball/spin"
readme = "README.md"
license-file = "LICENSE"

edition = "2021"
default-run = "spin"


[lib]
name = "spin"
path = "src/lib.rs"

[[bin]]
name = "spin"
path = "src/bin.rs"

[[bin]]
name = "spin-id-gen"
path = "src/tools/spin-id-gen.rs"

[[bin]]
name = "spin-dmd-font"
path = "src/tools/spin-dmd-font.rs"

[[test]]
name = "lua-tests"
path = "tests/test_lua.rs"
harness = false

[features]
default = ["sdl", "proc"]
sdl = ["dep:sdl2"]
proc = ["dep:bindgen"]
debug_audio = []
debug_faults = []
debug_fps = []
debug_monitor = []
debug_render = []

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.5.13", features = ["cargo", "derive"] }
ctrlc = "3.4.5"
figment = { version = "0.10.19", features = [ "yaml" ] }
home = "0.5.11"
mlua = { version = "~0.10.2", features = ["lua54", "serialize"] }
rustyline = "15.0.0"
sdl2 = { version = "0.37", optional = true, features = ["ttf","image","gfx","mixer"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
serde_yml = "0.0.12"
termios = "0.3.3"
thiserror = "2.0.11"

[build-dependencies]
bindgen = { version = "0.71.0", optional = true }