[package]
name = "spin"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "~0.10.2", features = ["lua54"] }
sdl2 = { version = "0.37",    features = ["ttf","image","gfx","mixer"] }

