vars:
  - { name: credits, kind: !int 0 }
  - { name: free_play, kind: !bool false }
  - { name: game_active, kind: !bool false }

scripts:
  - { name: "start_game", module: "game" }
  - { name: "start_service", module: "game" }
  - { name: "add_player", module: "game" }
