vars:
  - { name: credits, kind: !int 0 }
  - { name: free_play, kind: !bool false }
  - { name: game_active, kind: !bool false }

scripts:
  std_start_game:     { module: "std_game" }
  std_start_service:  { module: "std_game" }
  std_add_player:     { module: "std_game" }


