vars:
  credits:      { kind: !int 0 }
  free_play:    { kind: !bool false }
  game_active:  { kind: !bool false }

scripts:
  start_game:     { module: "_game" }
  start_service:  { module: "_game" }
  add_player:     { module: "_game" }


