namespaces:
  player:
    score:                      { kind: !int 0 }
    extra_balls_awarded:        { kind: !int 0 }
    total_extra_balls_awarded:  { kind: !int 0 }
    replay_awarded:             { kind: !bool false }


vars:
  credits:        { kind: !int 0 }
  free_play:      { kind: !bool false }
  game_active:    { kind: !bool false }
  player:         { kind: !int 1 }
  ball:           { kind: !int 1 }
  is_extra_ball:  { kind: !bool false }
  player_count:   { kind: !int 1 }


scripts:
  start_game:     { module: "_game" }
  start_service:  { module: "_game" }
  add_player:     { module: "_game" }

  test_start_service_no_credits:    { module: "_game_test", test: true }
  test_start_service_player_4:      { module: "_game_test", test: true }

run_groups:
  service: {}
  main: {}
  game: { parent: main }
  turn: { parent: game }
  ball: { parent: turn }
  mode: { parent: ball }

