namespaces:
  player:
    score:                      { kind: !int 0 }
    ball:                       { kind: !int 1 }
    extra_balls_awarded:        { kind: !int 0 }
    total_extra_balls_awarded:  { kind: !int 0 }
    replay_awarded:             { kind: !bool false }


vars:
  credits:      { kind: !int 0 }
  free_play:    { kind: !bool false }
  game_active:  { kind: !bool false }
  player:       { kind: !int 0 }
  player_count: { kind: !int 0 }


scripts:
  start_game:     { module: "_game" }
  start_service:  { module: "_game" }
  add_player:     { module: "_game" }

run_groups:
  service: {}
  main: {}
  game: { parent: main }
  turn: { parent: game }
  ball: { parent: turn }
  mode: { parent: ball }

