vars:
  max_players: { kind: !int 4 }

  player_1: { kind: !namespace { name: player } }
  player_2: { kind: !namespace { name: player } }
  player_3: { kind: !namespace { name: player } }
  player_4: { kind: !namespace { name: player } }
