namespaces:
  player:
    score:                      { kind: !int 0 }
    ball:                       { kind: !int 1 }
    extra_balls_awarded:        { kind: !int 0 }
    total_extra_balls_awarded:  { kind: !int 0 }
    replay_awarded:             { kind: !bool false }

vars:
  player:       { kind: !int 0 }
  player_count: { kind: !int 0 }
