vars:
  max_players: { kind: !int 4 }

  player1: { kind: !namespace { name: player } }
  player2: { kind: !namespace { name: player } }
  player3: { kind: !namespace { name: player } }
  player4: { kind: !namespace { name: player } }
