vars:
  - { name: max_players, kind: !int 4 }

  - { name: player1, kind: !namespace { name: player } }
  - { name: player2, kind: !namespace { name: player } }
  - { name: player3, kind: !namespace { name: player } }
  - { name: player4, kind: !namespace { name: player } }
