services:
  redis:
    name: spin-redis
    hostname: spin-redis
    container_name: spin-redis
    build: ./container/spin-redis
    command: redis-server /usr/local/etc/redis.conf
    ports:
      - 1080:6379
    networks:
      - spin

networks:
  spin:
    name: spin

