local pub = {}

pub.ADD_PLAYER = "add_player"
pub.CREDITS = "credits"
pub.CREDITS_REQUIRED = "credits_required"
pub.DMD = "dmd"
pub.DMD_04B_03_7PX = "dmd_04b_03_7px"
pub.DMD_18X10 = "dmd_18x10"
pub.DMD_18X11 = "dmd_18x11"
pub.DMD_18X12 = "dmd_18x12"
pub.DMD_14X10 = "dmd_14x10"
pub.DMD_14X9 = "dmd_14x9"
pub.DMD_14X8 = "dmd_14x8"
pub.DMD_09X7 = "dmd_09x7"
pub.DMD_09X6 = "dmd_09x6"
pub.DMD_09X7 = "dmd_09x5"
pub.FREE_PLAY = "free_play"
pub.GAME_ACTIVE = "game_active"
pub.GAME_FULL = "game_full"
pub.MAX_PLAYERS = "max_players"
pub.PLAYER = "player"
pub.PLAYER_1 = "player_1"
pub.PLAYER_2 = "player_2"
pub.PLAYER_3 = "player_3"
pub.PLAYER_4 = "player_4"
pub.PLAYER_COUNT = "player_count"
pub.REJECTED = "rejected"
pub.SCORE = "score"
pub.START_BUTTON = "start_button"
pub.START_SERVICE = "start_service"
pub.START_GAME = "start_game"
pub.TEST_OK = "test_ok"
pub.TICK = "tick"
pub.WAKE = "wake"

package.loaded["std"] = pub

return pub
