/* automatically generated by rust-bindgen 0.71.1 */

pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2X: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C2X_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 39;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const _BITS_STDINT_LEAST_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const kPRSuccess: u32 = 1;
pub const kPRFailure: u32 = 0;
pub const kPRHandleInvalid: u32 = 0;
pub const P_ROC_INIT_PATTERN_A: u32 = 2149519650;
pub const P_ROC_INIT_PATTERN_B: u32 = 878082219;
pub const P_ROC_CHIP_ID: u32 = 4276993775;
pub const P3_ROC_CHIP_ID: u32 = 4080907071;
pub const P_ROC_VER_REV_FIXED_SWITCH_STATE_READS: u32 = 65555;
pub const P_ROC_AUTO_STERN_DETECT_SHIFT: u32 = 8;
pub const P_ROC_AUTO_STERN_DETECT_MASK: u32 = 256;
pub const P_ROC_AUTO_STERN_DETECT_VALUE: u32 = 1;
pub const P_ROC_MANUAL_STERN_DETECT_SHIFT: u32 = 0;
pub const P_ROC_MANUAL_STERN_DETECT_MASK: u32 = 1;
pub const P_ROC_MANUAL_STERN_DETECT_VALUE: u32 = 0;
pub const P_ROC_BOARD_VERSION_SHIFT: u32 = 7;
pub const P_ROC_BOARD_VERSION_MASK: u32 = 128;
pub const P_ROC_ADDR_MASK: u32 = 1048575;
pub const P_ROC_HEADER_LENGTH_MASK: u32 = 2146435072;
pub const P_ROC_COMMAND_MASK: u32 = 2147483648;
pub const P_ROC_ADDR_SHIFT: u32 = 0;
pub const P_ROC_HEADER_LENGTH_SHIFT: u32 = 20;
pub const P_ROC_COMMAND_SHIFT: u32 = 31;
pub const P_ROC_READ: u32 = 0;
pub const P_ROC_WRITE: u32 = 1;
pub const P_ROC_REQUESTED_DATA: u32 = 0;
pub const P_ROC_UNREQUESTED_DATA: u32 = 1;
pub const P_ROC_REG_ADDR_MASK: u32 = 65535;
pub const P_ROC_MODULE_SELECT_MASK: u32 = 983040;
pub const P_ROC_REG_ADDR_SHIFT: u32 = 0;
pub const P_ROC_MODULE_SELECT_SHIFT: u32 = 16;
pub const P_ROC_MANAGER_SELECT: u32 = 0;
pub const P_ROC_BUS_JTAG_SELECT: u32 = 1;
pub const P_ROC_BUS_SWITCH_CTRL_SELECT: u32 = 2;
pub const P_ROC_BUS_DRIVER_CTRL_SELECT: u32 = 3;
pub const P_ROC_BUS_STATE_CHANGE_PROC_SELECT: u32 = 4;
pub const P_ROC_BUS_DMD_SELECT: u32 = 5;
pub const P_ROC_BUS_UNASSOCIATED_SELECT: u32 = 15;
pub const P3_ROC_MANAGER_SELECT: u32 = 0;
pub const P3_ROC_BUS_SPI_SELECT: u32 = 1;
pub const P3_ROC_BUS_SWITCH_CTRL_SELECT: u32 = 2;
pub const P3_ROC_BUS_DRIVER_CTRL_SELECT: u32 = 3;
pub const P3_ROC_BUS_STATE_CHANGE_PROC_SELECT: u32 = 4;
pub const P3_ROC_BUS_AUX_CTRL_SELECT: u32 = 5;
pub const P3_ROC_BUS_ACCELEROMETER_SELECT: u32 = 6;
pub const P3_ROC_BUS_I2C_SELECT: u32 = 7;
pub const P3_ROC_BUS_UNASSOCIATED_SELECT: u32 = 15;
pub const P_ROC_REG_CHIP_ID_ADDR: u32 = 0;
pub const P_ROC_REG_VERSION_ADDR: u32 = 1;
pub const P_ROC_REG_WATCHDOG_ADDR: u32 = 2;
pub const P_ROC_REG_DIPSWITCH_ADDR: u32 = 3;
pub const P_ROC_MANAGER_WATCHDOG_EXPIRED_SHIFT: u32 = 30;
pub const P_ROC_MANAGER_WATCHDOG_ENABLE_SHIFT: u32 = 14;
pub const P_ROC_MANAGER_WATCHDOG_RESET_TIME_SHIFT: u32 = 0;
pub const P_ROC_MANAGER_REUSE_DMD_DATA_FOR_AUX_SHIFT: u32 = 10;
pub const P_ROC_MANAGER_INVERT_DIPSWITCH_1_SHIFT: u32 = 9;
pub const P3_ROC_SPI_OPCODE_SHIFT: u32 = 24;
pub const P3_ROC_SPI_OPCODE_WR_ENABLE: u32 = 0;
pub const P3_ROC_SPI_OPCODE_WR_DISABLE: u32 = 1;
pub const P3_ROC_SPI_OPCODE_RD_ID: u32 = 2;
pub const P3_ROC_SPI_OPCODE_RD_STATUS: u32 = 3;
pub const P3_ROC_SPI_OPCODE_WR_STATUS: u32 = 4;
pub const P3_ROC_SPI_OPCODE_RD_DATA: u32 = 5;
pub const P3_ROC_SPI_OPCODE_FRD_DATA: u32 = 6;
pub const P3_ROC_SPI_OPCODE_PP: u32 = 7;
pub const P3_ROC_SPI_OPCODE_SECTOR_ERASE: u32 = 8;
pub const P3_ROC_SPI_OPCODE_BULK_ERASE: u32 = 9;
pub const P3_ROC_SPI_OPCODE_DEEP_POWERDN: u32 = 10;
pub const P3_ROC_SPI_OPCODE_RELEASE: u32 = 11;
pub const P_ROC_JTAG_SHIFT_EXIT_SHIFT: u32 = 16;
pub const P_ROC_JTAG_SHIFT_NUM_BITS_SHIFT: u32 = 0;
pub const P_ROC_JTAG_CMD_CHANGE_STATE: u32 = 0;
pub const P_ROC_JTAG_CMD_SHIFT: u32 = 1;
pub const P_ROC_JTAG_CMD_TRANSITION: u32 = 2;
pub const P_ROC_JTAG_CMD_SET_PORTS: u32 = 3;
pub const P_ROC_JTAG_CMD_START_SHIFT: u32 = 31;
pub const P_ROC_JTAG_CMD_OE_SHIFT: u32 = 30;
pub const P_ROC_JTAG_CMD_CMD_SHIFT: u32 = 24;
pub const P_ROC_JTAG_TRANSITION_TCK_MASK_SHIFT: u32 = 6;
pub const P_ROC_JTAG_TRANSITION_TDO_MASK_SHIFT: u32 = 5;
pub const P_ROC_JTAG_TRANSITION_TMS_MASK_SHIFT: u32 = 4;
pub const P_ROC_JTAG_TRANSITION_TCK_SHIFT: u32 = 2;
pub const P_ROC_JTAG_TRANSITION_TDO_SHIFT: u32 = 1;
pub const P_ROC_JTAG_TRANSITION_TMS_SHIFT: u32 = 0;
pub const P_ROC_JTAG_STATUS_DONE_SHIFT: u32 = 31;
pub const P_ROC_JTAG_STATUS_TDI_SHIFT: u32 = 16;
pub const P_ROC_JTAG_COMMAND_REG_BASE_ADDR: u32 = 0;
pub const P_ROC_JTAG_STATUS_REG_BASE_ADDR: u32 = 1;
pub const P_ROC_JTAG_TDO_MEMORY_BASE_ADDR: u32 = 1024;
pub const P_ROC_JTAG_TDI_MEMORY_BASE_ADDR: u32 = 2048;
pub const P_ROC_SWITCH_CTRL_STATE_BASE_ADDR: u32 = 4;
pub const P_ROC_SWITCH_CTRL_OLD_DEBOUNCE_BASE_ADDR: u32 = 11;
pub const P_ROC_SWITCH_CTRL_DEBOUNCE_BASE_ADDR: u32 = 12;
pub const P3_ROC_SWITCH_CTRL_STATE_BASE_ADDR: u32 = 16;
pub const P3_ROC_SWITCH_CTRL_DEBOUNCE_BASE_ADDR: u32 = 32;
pub const P_ROC_EVENT_TYPE_SWITCH: u32 = 0;
pub const P_ROC_EVENT_TYPE_DMD: u32 = 1;
pub const P_ROC_EVENT_TYPE_BURST_SWITCH: u32 = 2;
pub const P_ROC_EVENT_TYPE_ACCELEROMETER: u32 = 3;
pub const P_ROC_V1_EVENT_TYPE_MASK: u32 = 3072;
pub const P_ROC_V1_EVENT_TYPE_SHIFT: u32 = 10;
pub const P_ROC_V2_EVENT_TYPE_MASK: u32 = 49152;
pub const P_ROC_V2_EVENT_TYPE_SHIFT: u32 = 14;
pub const P_ROC_V1_EVENT_SWITCH_NUM_MASK: u32 = 255;
pub const P_ROC_V2_EVENT_SWITCH_NUM_MASK: u32 = 2047;
pub const P_ROC_V1_EVENT_SWITCH_STATE_MASK: u32 = 256;
pub const P_ROC_V2_EVENT_SWITCH_STATE_MASK: u32 = 4096;
pub const P_ROC_V1_EVENT_SWITCH_STATE_SHIFT: u32 = 8;
pub const P_ROC_V2_EVENT_SWITCH_STATE_SHIFT: u32 = 12;
pub const P_ROC_V1_EVENT_SWITCH_DEBOUNCED_MASK: u32 = 512;
pub const P_ROC_V2_EVENT_SWITCH_DEBOUNCED_MASK: u32 = 8192;
pub const P_ROC_V1_EVENT_SWITCH_DEBOUNCED_SHIFT: u32 = 9;
pub const P_ROC_V2_EVENT_SWITCH_DEBOUNCED_SHIFT: u32 = 13;
pub const P_ROC_V1_EVENT_SWITCH_TIMESTAMP_MASK: u32 = 4294963200;
pub const P_ROC_V1_EVENT_SWITCH_TIMESTAMP_SHIFT: u32 = 12;
pub const P_ROC_V2_EVENT_SWITCH_TIMESTAMP_MASK: u32 = 4294901760;
pub const P_ROC_V2_EVENT_SWITCH_TIMESTAMP_SHIFT: u32 = 16;
pub const P_ROC_V2_EVENT_ACCEL_TIMESTAMP_MASK: u32 = 4294705152;
pub const P_ROC_V2_EVENT_ACCEL_TIMESTAMP_SHIFT: u32 = 18;
pub const P_ROC_DRIVER_CTRL_DECODE_SHIFT: u32 = 10;
pub const P_ROC_DRIVER_CTRL_REG_DECODE: u32 = 0;
pub const P_ROC_DRIVER_CONFIG_TABLE_DECODE: u32 = 1;
pub const P_ROC_DRIVER_AUX_MEM_DECODE: u32 = 2;
pub const P_ROC_DRIVER_CATCHALL_DECODE: u32 = 3;
pub const P_ROC_DRIVER_GLOBAL_ENABLE_DIRECT_OUTPUTS_SHIFT: u32 = 31;
pub const P_ROC_DRIVER_GLOBAL_GLOBAL_POLARITY_SHIFT: u32 = 30;
pub const P_ROC_DRIVER_GLOBAL_USE_CLEAR_SHIFT: u32 = 28;
pub const P_ROC_DRIVER_GLOBAL_STROBE_START_SELECT_SHIFT: u32 = 27;
pub const P_ROC_DRIVER_GLOBAL_START_STROBE_TIME_SHIFT: u32 = 20;
pub const P_ROC_DRIVER_GLOBAL_START_STROBE_TIME_MASK: u32 = 133169152;
pub const P_ROC_DRIVER_GLOBAL_MATRIX_ROW_ENABLE_INDEX_1_SHIFT: u32 = 16;
pub const P_ROC_DRIVER_GLOBAL_MATRIX_ROW_ENABLE_INDEX_1_MASK: u32 = 983040;
pub const P_ROC_DRIVER_GLOBAL_MATRIX_ROW_ENABLE_INDEX_0_SHIFT: u32 = 12;
pub const P_ROC_DRIVER_GLOBAL_MATRIX_ROW_ENABLE_INDEX_0_MASK: u32 = 61440;
pub const P_ROC_DRIVER_GLOBAL_ACTIVE_LOW_MATRIX_ROWS_SHIFT: u32 = 11;
pub const P_ROC_DRIVER_GLOBAL_ENCODE_ENABLES_SHIFT: u32 = 10;
pub const P_ROC_DRIVER_GLOBAL_TICKLE_WATCHDOG_SHIFT: u32 = 9;
pub const P_ROC_DRIVER_GROUP_SLOW_TIME_SHIFT: u32 = 12;
pub const P_ROC_DRIVER_GROUP_DISABLE_STROBE_AFTER_SHIFT: u32 = 11;
pub const P_ROC_DRIVER_GROUP_ENABLE_INDEX_SHIFT: u32 = 7;
pub const P_ROC_DRIVER_GROUP_ROW_ACTIVATE_INDEX_SHIFT: u32 = 4;
pub const P_ROC_DRIVER_GROUP_ROW_ENABLE_SELECT_SHIFT: u32 = 3;
pub const P_ROC_DRIVER_GROUP_MATRIXED_SHIFT: u32 = 2;
pub const P_ROC_DRIVER_GROUP_POLARITY_SHIFT: u32 = 1;
pub const P_ROC_DRIVER_GROUP_ACTIVE_SHIFT: u32 = 0;
pub const P_ROC_DRIVER_CONFIG_OUTPUT_DRIVE_TIME_SHIFT: u32 = 0;
pub const P_ROC_DRIVER_CONFIG_POLARITY_SHIFT: u32 = 8;
pub const P_ROC_DRIVER_CONFIG_STATE_SHIFT: u32 = 9;
pub const P_ROC_DRIVER_CONFIG_UPDATE_SHIFT: u32 = 10;
pub const P_ROC_DRIVER_CONFIG_WAIT_4_1ST_SLOT_SHIFT: u32 = 11;
pub const P_ROC_DRIVER_CONFIG_TIMESLOT_SHIFT: u32 = 16;
pub const P_ROC_DRIVER_CONFIG_PATTER_ON_TIME_SHIFT: u32 = 16;
pub const P_ROC_DRIVER_CONFIG_PATTER_OFF_TIME_SHIFT: u32 = 23;
pub const P_ROC_DRIVER_CONFIG_PATTER_ENABLE_SHIFT: u32 = 30;
pub const P_ROC_DRIVER_CONFIG_FUTURE_ENABLE_SHIFT: u32 = 31;
pub const P_ROC_DRIVER_CONFIG_TABLE_DRIVER_NUM_SHIFT: u32 = 1;
pub const P_ROC_DRIVER_AUX_ENTRY_ACTIVE_SHIFT: u32 = 31;
pub const P_ROC_DRIVER_AUX_OUTPUT_DELAY_SHIFT: u32 = 20;
pub const P_ROC_DRIVER_AUX_OUTPUT_DELAY_MASK: u32 = 2047;
pub const P_ROC_DRIVER_AUX_MUX_ENABLES_SHIFT: u32 = 19;
pub const P_ROC_DRIVER_AUX_COMMAND_SHIFT: u32 = 16;
pub const P_ROC_DRIVER_AUX_COMMAND_MASK: u32 = 3;
pub const P_ROC_DRIVER_AUX_ENABLES_SHIFT: u32 = 12;
pub const P_ROC_DRIVER_AUX_ENABLES_MASK: u32 = 15;
pub const P_ROC_DRIVER_AUX_EXTRA_DATA_SHIFT: u32 = 8;
pub const P_ROC_DRIVER_AUX_EXTRA_DATA_MASK: u32 = 15;
pub const P_ROC_DRIVER_AUX_DATA_SHIFT: u32 = 0;
pub const P_ROC_DRIVER_AUX_DATA_MASK: u32 = 255;
pub const P_ROC_DRIVER_AUX_DELAY_TIME_SHIFT: u32 = 0;
pub const P_ROC_DRIVER_AUX_DELAY_TIME_MASK: u32 = 16383;
pub const P_ROC_DRIVER_AUX_JUMP_ADDR_SHIFT: u32 = 0;
pub const P_ROC_DRIVER_AUX_JUMP_ADDR_MASK: u32 = 255;
pub const P_ROC_DRIVER_AUX_CMD_OUTPUT: u32 = 2;
pub const P_ROC_DRIVER_AUX_CMD_DELAY: u32 = 1;
pub const P_ROC_DRIVER_AUX_CMD_JUMP: u32 = 0;
pub const P_ROC_SWITCH_CONFIG_CLEAR_SHIFT: u32 = 31;
pub const P_ROC_SWITCH_CONFIG_USE_COLUMN_9: u32 = 30;
pub const P_ROC_SWITCH_CONFIG_USE_COLUMN_8: u32 = 29;
pub const P_ROC_SWITCH_CONFIG_MS_PER_DM_SCAN_LOOP_SHIFT: u32 = 24;
pub const P_ROC_SWITCH_CONFIG_PULSES_BEFORE_CHECKING_RX_SHIFT: u32 = 18;
pub const P_ROC_SWITCH_CONFIG_INACTIVE_PULSES_AFTER_BURST_SHIFT: u32 = 12;
pub const P_ROC_SWITCH_CONFIG_PULSES_PER_BURST_SHIFT: u32 = 6;
pub const P_ROC_SWITCH_CONFIG_MS_PER_PULSE_HALF_PERIOD_SHIFT: u32 = 0;
pub const P_ROC_SWITCH_RULE_DRIVE_OUTPUTS_NOW: u32 = 13;
pub const P_ROC_SWITCH_RULE_NUM_DEBOUNCE_SHIFT: u32 = 9;
pub const P_ROC_SWITCH_RULE_NUM_STATE_SHIFT: u32 = 8;
pub const P_ROC_SWITCH_RULE_NUM_SWITCH_NUM_SHIFT: u32 = 0;
pub const P_ROC_SWITCH_RULE_NUM_TO_ADDR_SHIFT: u32 = 2;
pub const P_ROC_SWITCH_RULE_RELOAD_ACTIVE_SHIFT: u32 = 31;
pub const P_ROC_SWITCH_RULE_NOTIFY_HOST_SHIFT: u32 = 23;
pub const P_ROC_SWITCH_RULE_LINK_ACTIVE_SHIFT: u32 = 10;
pub const P_ROC_SWITCH_RULE_LINK_ADDRESS_SHIFT: u32 = 11;
pub const P_ROC_SWITCH_RULE_CHANGE_OUTPUT_SHIFT: u32 = 9;
pub const P_ROC_SWITCH_RULE_DRIVER_NUM_SHIFT: u32 = 0;
pub const P_ROC_STATE_CHANGE_CONFIG_ADDR: u32 = 4096;
pub const P_ROC_DMD_NUM_COLUMNS_SHIFT: u32 = 0;
pub const P_ROC_DMD_NUM_ROWS_SHIFT: u32 = 8;
pub const P_ROC_DMD_NUM_SUB_FRAMES_SHIFT: u32 = 16;
pub const P_ROC_DMD_NUM_FRAME_BUFFERS_SHIFT: u32 = 24;
pub const P_ROC_DMD_AUTO_INC_WR_POINTER_SHIFT: u32 = 29;
pub const P_ROC_DMD_ENABLE_FRAME_EVENTS_SHIFT: u32 = 30;
pub const P_ROC_DMD_ENABLE_SHIFT: u32 = 31;
pub const P_ROC_DMD_DOTCLK_HALF_PERIOD_SHIFT: u32 = 0;
pub const P_ROC_DMD_DE_HIGH_CYCLES_SHIFT: u32 = 6;
pub const P_ROC_DMD_LATCH_HIGH_CYCLES_SHIFT: u32 = 16;
pub const P_ROC_DMD_RCLK_LOW_CYCLES_SHIFT: u32 = 24;
pub const P_ROC_DMD_DOT_TABLE_BASE_ADDR: u32 = 4096;
pub const P_ROC_DRIVER_PDB_ADDR: u32 = 3072;
pub const P_ROC_DRIVER_PDB_COMMAND_SHIFT: u32 = 24;
pub const P_ROC_DRIVER_PDB_BOARD_ADDR_SHIFT: u32 = 16;
pub const P_ROC_DRIVER_PDB_REGISTER_SHIFT: u32 = 8;
pub const P_ROC_DRIVER_PDB_DATA_SHIFT: u32 = 0;
pub const P_ROC_DRIVER_PDB_READ_COMMAND: u32 = 0;
pub const P_ROC_DRIVER_PDB_WRITE_COMMAND: u32 = 1;
pub const P_ROC_DRIVER_PDB_CLEAR_ALL_COMMAND: u32 = 7;
pub const P_ROC_DRIVER_PDB_BROADCAST_ADDR: u32 = 63;
pub const p_ROC_DRIVER_PDB_REGISTER_BANK_A: u32 = 0;
pub const p_ROC_DRIVER_PDB_REGISTER_BANK_B: u32 = 1;
pub const kPRResetFlagDefault: u32 = 0;
pub const kPRResetFlagUpdateDevice: u32 = 1;
pub const kPRDriverGroupsMax: u32 = 26;
pub const kPRDriverCount: u32 = 256;
pub const kPRDriverAuxCmdOutput: u32 = 2;
pub const kPRDriverAuxCmdDelay: u32 = 1;
pub const kPRDriverAuxCmdJump: u32 = 0;
pub const kPRSwitchPhysicalFirst: u32 = 0;
pub const kPRSwitchPhysicalLast: u32 = 255;
pub const kPRSwitchNeverDebounceFirst: u32 = 192;
pub const kPRSwitchNeverDebounceLast: u32 = 255;
pub const kPRSwitchCount: u32 = 256;
pub const kPRSwitchRulesCount: u32 = 1024;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __fsid_t"][::std::mem::size_of::<__fsid_t>() - 8usize];
    ["Alignment of __fsid_t"][::std::mem::align_of::<__fsid_t>() - 4usize];
    ["Offset of field: __fsid_t::__val"][::std::mem::offset_of!(__fsid_t, __val) - 0usize];
};
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type bool_t = i32;
pub type PRResult = i32;
pub type PRHandle = *mut ::std::os::raw::c_void;
pub const PRLogLevel_kPRLogVerbose: PRLogLevel = 0;
pub const PRLogLevel_kPRLogInfo: PRLogLevel = 1;
pub const PRLogLevel_kPRLogWarning: PRLogLevel = 2;
pub const PRLogLevel_kPRLogError: PRLogLevel = 3;
pub type PRLogLevel = ::std::os::raw::c_uint;
pub type PRLogCallback = ::std::option::Option<
    unsafe extern "C" fn(level: PRLogLevel, text: *const ::std::os::raw::c_char),
>;
unsafe extern "C" {
    pub fn PRLogSetCallback(callback: PRLogCallback);
}
unsafe extern "C" {
    pub fn PRLogSetLevel(level: PRLogLevel);
}
unsafe extern "C" {
    pub fn PRGetLastErrorText() -> *const ::std::os::raw::c_char;
}
pub const PRMachineType_kPRMachineInvalid: PRMachineType = 0;
pub const PRMachineType_kPRMachineCustom: PRMachineType = 1;
pub const PRMachineType_kPRMachineWPCAlphanumeric: PRMachineType = 2;
pub const PRMachineType_kPRMachineWPC: PRMachineType = 3;
pub const PRMachineType_kPRMachineWPC95: PRMachineType = 4;
pub const PRMachineType_kPRMachineSternWhitestar: PRMachineType = 5;
pub const PRMachineType_kPRMachineSternSAM: PRMachineType = 6;
pub const PRMachineType_kPRMachinePDB: PRMachineType = 7;
pub type PRMachineType = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn PRCreate(machineType: PRMachineType) -> PRHandle;
}
unsafe extern "C" {
    pub fn PRDelete(handle: PRHandle);
}
unsafe extern "C" {
    pub fn PRReset(handle: PRHandle, resetFlags: u32) -> PRResult;
}
unsafe extern "C" {
    pub fn PRFlushWriteData(handle: PRHandle) -> PRResult;
}
unsafe extern "C" {
    pub fn PRWriteData(
        handle: PRHandle,
        moduleSelect: u32,
        startingAddr: u32,
        numWriteWords: i32,
        writeBuffer: *mut u32,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRWriteDataUnbuffered(
        handle: PRHandle,
        moduleSelect: u32,
        startingAddr: u32,
        numWriteWords: i32,
        writeBuffer: *mut u32,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRReadData(
        handle: PRHandle,
        moduleSelect: u32,
        startingAddr: u32,
        numReadWords: i32,
        readBuffer: *mut u32,
    ) -> PRResult;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PRManagerConfig {
    pub reuse_dmd_data_for_aux: bool_t,
    pub invert_dipswitch_1: bool_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PRManagerConfig"][::std::mem::size_of::<PRManagerConfig>() - 8usize];
    ["Alignment of PRManagerConfig"][::std::mem::align_of::<PRManagerConfig>() - 4usize];
    ["Offset of field: PRManagerConfig::reuse_dmd_data_for_aux"]
        [::std::mem::offset_of!(PRManagerConfig, reuse_dmd_data_for_aux) - 0usize];
    ["Offset of field: PRManagerConfig::invert_dipswitch_1"]
        [::std::mem::offset_of!(PRManagerConfig, invert_dipswitch_1) - 4usize];
};
unsafe extern "C" {
    pub fn PRManagerUpdateConfig(handle: PRHandle, managerConfig: *mut PRManagerConfig)
        -> PRResult;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PRDriverGlobalConfig {
    pub enableOutputs: bool_t,
    pub globalPolarity: bool_t,
    pub useClear: bool_t,
    pub strobeStartSelect: bool_t,
    pub startStrobeTime: u8,
    pub matrixRowEnableIndex1: u8,
    pub matrixRowEnableIndex0: u8,
    pub activeLowMatrixRows: bool_t,
    pub encodeEnables: bool_t,
    pub tickleSternWatchdog: bool_t,
    pub watchdogExpired: bool_t,
    pub watchdogEnable: bool_t,
    pub watchdogResetTime: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PRDriverGlobalConfig"][::std::mem::size_of::<PRDriverGlobalConfig>() - 44usize];
    ["Alignment of PRDriverGlobalConfig"][::std::mem::align_of::<PRDriverGlobalConfig>() - 4usize];
    ["Offset of field: PRDriverGlobalConfig::enableOutputs"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, enableOutputs) - 0usize];
    ["Offset of field: PRDriverGlobalConfig::globalPolarity"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, globalPolarity) - 4usize];
    ["Offset of field: PRDriverGlobalConfig::useClear"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, useClear) - 8usize];
    ["Offset of field: PRDriverGlobalConfig::strobeStartSelect"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, strobeStartSelect) - 12usize];
    ["Offset of field: PRDriverGlobalConfig::startStrobeTime"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, startStrobeTime) - 16usize];
    ["Offset of field: PRDriverGlobalConfig::matrixRowEnableIndex1"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, matrixRowEnableIndex1) - 17usize];
    ["Offset of field: PRDriverGlobalConfig::matrixRowEnableIndex0"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, matrixRowEnableIndex0) - 18usize];
    ["Offset of field: PRDriverGlobalConfig::activeLowMatrixRows"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, activeLowMatrixRows) - 20usize];
    ["Offset of field: PRDriverGlobalConfig::encodeEnables"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, encodeEnables) - 24usize];
    ["Offset of field: PRDriverGlobalConfig::tickleSternWatchdog"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, tickleSternWatchdog) - 28usize];
    ["Offset of field: PRDriverGlobalConfig::watchdogExpired"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, watchdogExpired) - 32usize];
    ["Offset of field: PRDriverGlobalConfig::watchdogEnable"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, watchdogEnable) - 36usize];
    ["Offset of field: PRDriverGlobalConfig::watchdogResetTime"]
        [::std::mem::offset_of!(PRDriverGlobalConfig, watchdogResetTime) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PRDriverGroupConfig {
    pub groupNum: u8,
    pub slowTime: u16,
    pub enableIndex: u8,
    pub rowActivateIndex: u8,
    pub rowEnableSelect: u8,
    pub matrixed: bool_t,
    pub polarity: bool_t,
    pub active: bool_t,
    pub disableStrobeAfter: bool_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PRDriverGroupConfig"][::std::mem::size_of::<PRDriverGroupConfig>() - 24usize];
    ["Alignment of PRDriverGroupConfig"][::std::mem::align_of::<PRDriverGroupConfig>() - 4usize];
    ["Offset of field: PRDriverGroupConfig::groupNum"]
        [::std::mem::offset_of!(PRDriverGroupConfig, groupNum) - 0usize];
    ["Offset of field: PRDriverGroupConfig::slowTime"]
        [::std::mem::offset_of!(PRDriverGroupConfig, slowTime) - 2usize];
    ["Offset of field: PRDriverGroupConfig::enableIndex"]
        [::std::mem::offset_of!(PRDriverGroupConfig, enableIndex) - 4usize];
    ["Offset of field: PRDriverGroupConfig::rowActivateIndex"]
        [::std::mem::offset_of!(PRDriverGroupConfig, rowActivateIndex) - 5usize];
    ["Offset of field: PRDriverGroupConfig::rowEnableSelect"]
        [::std::mem::offset_of!(PRDriverGroupConfig, rowEnableSelect) - 6usize];
    ["Offset of field: PRDriverGroupConfig::matrixed"]
        [::std::mem::offset_of!(PRDriverGroupConfig, matrixed) - 8usize];
    ["Offset of field: PRDriverGroupConfig::polarity"]
        [::std::mem::offset_of!(PRDriverGroupConfig, polarity) - 12usize];
    ["Offset of field: PRDriverGroupConfig::active"]
        [::std::mem::offset_of!(PRDriverGroupConfig, active) - 16usize];
    ["Offset of field: PRDriverGroupConfig::disableStrobeAfter"]
        [::std::mem::offset_of!(PRDriverGroupConfig, disableStrobeAfter) - 20usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PRDriverState {
    pub driverNum: u16,
    pub outputDriveTime: u8,
    pub polarity: bool_t,
    pub state: bool_t,
    pub waitForFirstTimeSlot: bool_t,
    pub timeslots: u32,
    pub patterOnTime: u8,
    pub patterOffTime: u8,
    pub patterEnable: bool_t,
    pub futureEnable: bool_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PRDriverState"][::std::mem::size_of::<PRDriverState>() - 32usize];
    ["Alignment of PRDriverState"][::std::mem::align_of::<PRDriverState>() - 4usize];
    ["Offset of field: PRDriverState::driverNum"]
        [::std::mem::offset_of!(PRDriverState, driverNum) - 0usize];
    ["Offset of field: PRDriverState::outputDriveTime"]
        [::std::mem::offset_of!(PRDriverState, outputDriveTime) - 2usize];
    ["Offset of field: PRDriverState::polarity"]
        [::std::mem::offset_of!(PRDriverState, polarity) - 4usize];
    ["Offset of field: PRDriverState::state"]
        [::std::mem::offset_of!(PRDriverState, state) - 8usize];
    ["Offset of field: PRDriverState::waitForFirstTimeSlot"]
        [::std::mem::offset_of!(PRDriverState, waitForFirstTimeSlot) - 12usize];
    ["Offset of field: PRDriverState::timeslots"]
        [::std::mem::offset_of!(PRDriverState, timeslots) - 16usize];
    ["Offset of field: PRDriverState::patterOnTime"]
        [::std::mem::offset_of!(PRDriverState, patterOnTime) - 20usize];
    ["Offset of field: PRDriverState::patterOffTime"]
        [::std::mem::offset_of!(PRDriverState, patterOffTime) - 21usize];
    ["Offset of field: PRDriverState::patterEnable"]
        [::std::mem::offset_of!(PRDriverState, patterEnable) - 24usize];
    ["Offset of field: PRDriverState::futureEnable"]
        [::std::mem::offset_of!(PRDriverState, futureEnable) - 28usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PRDriverAuxCommand {
    pub active: bool_t,
    pub muxEnables: bool_t,
    pub command: u8,
    pub enables: u8,
    pub extraData: u8,
    pub data: u8,
    pub delayTime: u16,
    pub jumpAddr: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PRDriverAuxCommand"][::std::mem::size_of::<PRDriverAuxCommand>() - 16usize];
    ["Alignment of PRDriverAuxCommand"][::std::mem::align_of::<PRDriverAuxCommand>() - 4usize];
    ["Offset of field: PRDriverAuxCommand::active"]
        [::std::mem::offset_of!(PRDriverAuxCommand, active) - 0usize];
    ["Offset of field: PRDriverAuxCommand::muxEnables"]
        [::std::mem::offset_of!(PRDriverAuxCommand, muxEnables) - 4usize];
    ["Offset of field: PRDriverAuxCommand::command"]
        [::std::mem::offset_of!(PRDriverAuxCommand, command) - 8usize];
    ["Offset of field: PRDriverAuxCommand::enables"]
        [::std::mem::offset_of!(PRDriverAuxCommand, enables) - 9usize];
    ["Offset of field: PRDriverAuxCommand::extraData"]
        [::std::mem::offset_of!(PRDriverAuxCommand, extraData) - 10usize];
    ["Offset of field: PRDriverAuxCommand::data"]
        [::std::mem::offset_of!(PRDriverAuxCommand, data) - 11usize];
    ["Offset of field: PRDriverAuxCommand::delayTime"]
        [::std::mem::offset_of!(PRDriverAuxCommand, delayTime) - 12usize];
    ["Offset of field: PRDriverAuxCommand::jumpAddr"]
        [::std::mem::offset_of!(PRDriverAuxCommand, jumpAddr) - 14usize];
};
unsafe extern "C" {
    pub fn PRDriverUpdateGlobalConfig(
        handle: PRHandle,
        driverGlobalConfig: *mut PRDriverGlobalConfig,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverGetGroupConfig(
        handle: PRHandle,
        groupNum: u8,
        driverGroupConfig: *mut PRDriverGroupConfig,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverUpdateGroupConfig(
        handle: PRHandle,
        driverGroupConfig: *mut PRDriverGroupConfig,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverGetState(
        handle: PRHandle,
        driverNum: u8,
        driverState: *mut PRDriverState,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverUpdateState(handle: PRHandle, driverState: *mut PRDriverState) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverLoadMachineTypeDefaults(
        handle: PRHandle,
        machineType: PRMachineType,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverGroupDisable(handle: PRHandle, groupNum: u8) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverDisable(handle: PRHandle, driverNum: u8) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverPulse(handle: PRHandle, driverNum: u8, milliseconds: u8) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverFuturePulse(
        handle: PRHandle,
        driverNum: u8,
        milliseconds: u8,
        futureTime: u32,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverSchedule(
        handle: PRHandle,
        driverNum: u8,
        schedule: u32,
        cycleSeconds: u8,
        now: bool_t,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverPatter(
        handle: PRHandle,
        driverNum: u8,
        millisecondsOn: u8,
        millisecondsOff: u8,
        originalOnTime: u8,
        now: bool_t,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverPulsedPatter(
        handle: PRHandle,
        driverNum: u8,
        millisecondsOn: u8,
        millisecondsOff: u8,
        originalOnTime: u8,
        now: bool_t,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverAuxPrepareOutput(
        auxCommand: *mut PRDriverAuxCommand,
        data: u8,
        extraData: u8,
        enables: u8,
        muxEnables: bool_t,
        delayTime: u16,
    );
}
unsafe extern "C" {
    pub fn PRDriverAuxPrepareDelay(auxCommand: *mut PRDriverAuxCommand, delayTime: u16);
}
unsafe extern "C" {
    pub fn PRDriverAuxPrepareJump(auxCommand: *mut PRDriverAuxCommand, jumpAddr: u8);
}
unsafe extern "C" {
    pub fn PRDriverAuxPrepareDisable(auxCommand: *mut PRDriverAuxCommand);
}
unsafe extern "C" {
    pub fn PRDriverWatchdogTickle(handle: PRHandle) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDriverGroupStateDisable(driverGroup: *mut PRDriverGroupConfig);
}
unsafe extern "C" {
    pub fn PRDriverStateDisable(driverState: *mut PRDriverState);
}
unsafe extern "C" {
    pub fn PRDriverStatePulse(driverState: *mut PRDriverState, milliseconds: u8);
}
unsafe extern "C" {
    pub fn PRDriverStateFuturePulse(
        driverState: *mut PRDriverState,
        milliseconds: u8,
        futureTime: u32,
    );
}
unsafe extern "C" {
    pub fn PRDriverStateSchedule(
        driverState: *mut PRDriverState,
        schedule: u32,
        cycleSeconds: u8,
        now: bool_t,
    );
}
unsafe extern "C" {
    pub fn PRDriverStatePatter(
        driverState: *mut PRDriverState,
        millisecondsOn: u8,
        millisecondsOff: u8,
        originalOnTime: u8,
        now: bool_t,
    );
}
unsafe extern "C" {
    pub fn PRDriverStatePulsedPatter(
        driverState: *mut PRDriverState,
        millisecondsOn: u8,
        millisecondsOff: u8,
        patterTime: u8,
        now: bool_t,
    );
}
unsafe extern "C" {
    pub fn PRDriverAuxSendCommands(
        handle: PRHandle,
        commands: *mut PRDriverAuxCommand,
        numCommands: u8,
        startingAddr: u8,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRDecode(machineType: PRMachineType, str_: *const ::std::os::raw::c_char) -> u16;
}
pub const PREventType_kPREventTypeInvalid: PREventType = 0;
pub const PREventType_kPREventTypeSwitchClosedDebounced: PREventType = 1;
pub const PREventType_kPREventTypeSwitchOpenDebounced: PREventType = 2;
pub const PREventType_kPREventTypeSwitchClosedNondebounced: PREventType = 3;
pub const PREventType_kPREventTypeSwitchOpenNondebounced: PREventType = 4;
pub const PREventType_kPREventTypeDMDFrameDisplayed: PREventType = 5;
pub const PREventType_kPREventTypeBurstSwitchOpen: PREventType = 6;
pub const PREventType_kPREventTypeBurstSwitchClosed: PREventType = 7;
pub const PREventType_kPREventTypeAccelerometerX: PREventType = 8;
pub const PREventType_kPREventTypeAccelerometerY: PREventType = 9;
pub const PREventType_kPREventTypeAccelerometerZ: PREventType = 10;
pub const PREventType_kPREventTypeAccelerometerIRQ: PREventType = 11;
pub const PREventType_kPREventTypetLast: PREventType = 4;
pub type PREventType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PREvent {
    pub type_: PREventType,
    pub value: u32,
    pub time: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PREvent"][::std::mem::size_of::<PREvent>() - 12usize];
    ["Alignment of PREvent"][::std::mem::align_of::<PREvent>() - 4usize];
    ["Offset of field: PREvent::type_"][::std::mem::offset_of!(PREvent, type_) - 0usize];
    ["Offset of field: PREvent::value"][::std::mem::offset_of!(PREvent, value) - 4usize];
    ["Offset of field: PREvent::time"][::std::mem::offset_of!(PREvent, time) - 8usize];
};
unsafe extern "C" {
    pub fn PRGetEvents(
        handle: PRHandle,
        eventsOut: *mut PREvent,
        maxEvents: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PRSwitchConfig {
    pub clear: bool_t,
    pub hostEventsEnable: bool_t,
    pub use_column_9: bool_t,
    pub use_column_8: bool_t,
    pub directMatrixScanLoopTime: u8,
    pub pulsesBeforeCheckingRX: u8,
    pub inactivePulsesAfterBurst: u8,
    pub pulsesPerBurst: u8,
    pub pulseHalfPeriodTime: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PRSwitchConfig"][::std::mem::size_of::<PRSwitchConfig>() - 24usize];
    ["Alignment of PRSwitchConfig"][::std::mem::align_of::<PRSwitchConfig>() - 4usize];
    ["Offset of field: PRSwitchConfig::clear"]
        [::std::mem::offset_of!(PRSwitchConfig, clear) - 0usize];
    ["Offset of field: PRSwitchConfig::hostEventsEnable"]
        [::std::mem::offset_of!(PRSwitchConfig, hostEventsEnable) - 4usize];
    ["Offset of field: PRSwitchConfig::use_column_9"]
        [::std::mem::offset_of!(PRSwitchConfig, use_column_9) - 8usize];
    ["Offset of field: PRSwitchConfig::use_column_8"]
        [::std::mem::offset_of!(PRSwitchConfig, use_column_8) - 12usize];
    ["Offset of field: PRSwitchConfig::directMatrixScanLoopTime"]
        [::std::mem::offset_of!(PRSwitchConfig, directMatrixScanLoopTime) - 16usize];
    ["Offset of field: PRSwitchConfig::pulsesBeforeCheckingRX"]
        [::std::mem::offset_of!(PRSwitchConfig, pulsesBeforeCheckingRX) - 17usize];
    ["Offset of field: PRSwitchConfig::inactivePulsesAfterBurst"]
        [::std::mem::offset_of!(PRSwitchConfig, inactivePulsesAfterBurst) - 18usize];
    ["Offset of field: PRSwitchConfig::pulsesPerBurst"]
        [::std::mem::offset_of!(PRSwitchConfig, pulsesPerBurst) - 19usize];
    ["Offset of field: PRSwitchConfig::pulseHalfPeriodTime"]
        [::std::mem::offset_of!(PRSwitchConfig, pulseHalfPeriodTime) - 20usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PRSwitchRule {
    pub reloadActive: bool_t,
    pub notifyHost: bool_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PRSwitchRule"][::std::mem::size_of::<PRSwitchRule>() - 8usize];
    ["Alignment of PRSwitchRule"][::std::mem::align_of::<PRSwitchRule>() - 4usize];
    ["Offset of field: PRSwitchRule::reloadActive"]
        [::std::mem::offset_of!(PRSwitchRule, reloadActive) - 0usize];
    ["Offset of field: PRSwitchRule::notifyHost"]
        [::std::mem::offset_of!(PRSwitchRule, notifyHost) - 4usize];
};
unsafe extern "C" {
    pub fn PRSwitchUpdateConfig(handle: PRHandle, switchConfig: *mut PRSwitchConfig) -> PRResult;
}
unsafe extern "C" {
    pub fn PRSwitchUpdateRule(
        handle: PRHandle,
        switchNum: u8,
        eventType: PREventType,
        rule: *mut PRSwitchRule,
        linkedDrivers: *mut PRDriverState,
        numDrivers: ::std::os::raw::c_int,
        drive_outputs_now: bool_t,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRSwitchGetStates(
        handle: PRHandle,
        switchStates: *mut PREventType,
        numSwitches: u16,
    ) -> PRResult;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PRDMDConfig {
    pub numRows: u8,
    pub numColumns: u16,
    pub numSubFrames: u8,
    pub numFrameBuffers: u8,
    pub autoIncBufferWrPtr: bool_t,
    pub enableFrameEvents: bool_t,
    pub enable: bool_t,
    pub rclkLowCycles: [u8; 8usize],
    pub latchHighCycles: [u8; 8usize],
    pub deHighCycles: [u16; 8usize],
    pub dotclkHalfPeriod: [u8; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PRDMDConfig"][::std::mem::size_of::<PRDMDConfig>() - 60usize];
    ["Alignment of PRDMDConfig"][::std::mem::align_of::<PRDMDConfig>() - 4usize];
    ["Offset of field: PRDMDConfig::numRows"]
        [::std::mem::offset_of!(PRDMDConfig, numRows) - 0usize];
    ["Offset of field: PRDMDConfig::numColumns"]
        [::std::mem::offset_of!(PRDMDConfig, numColumns) - 2usize];
    ["Offset of field: PRDMDConfig::numSubFrames"]
        [::std::mem::offset_of!(PRDMDConfig, numSubFrames) - 4usize];
    ["Offset of field: PRDMDConfig::numFrameBuffers"]
        [::std::mem::offset_of!(PRDMDConfig, numFrameBuffers) - 5usize];
    ["Offset of field: PRDMDConfig::autoIncBufferWrPtr"]
        [::std::mem::offset_of!(PRDMDConfig, autoIncBufferWrPtr) - 8usize];
    ["Offset of field: PRDMDConfig::enableFrameEvents"]
        [::std::mem::offset_of!(PRDMDConfig, enableFrameEvents) - 12usize];
    ["Offset of field: PRDMDConfig::enable"][::std::mem::offset_of!(PRDMDConfig, enable) - 16usize];
    ["Offset of field: PRDMDConfig::rclkLowCycles"]
        [::std::mem::offset_of!(PRDMDConfig, rclkLowCycles) - 20usize];
    ["Offset of field: PRDMDConfig::latchHighCycles"]
        [::std::mem::offset_of!(PRDMDConfig, latchHighCycles) - 28usize];
    ["Offset of field: PRDMDConfig::deHighCycles"]
        [::std::mem::offset_of!(PRDMDConfig, deHighCycles) - 36usize];
    ["Offset of field: PRDMDConfig::dotclkHalfPeriod"]
        [::std::mem::offset_of!(PRDMDConfig, dotclkHalfPeriod) - 52usize];
};
unsafe extern "C" {
    pub fn PRDMDUpdateConfig(handle: PRHandle, dmdConfig: *mut PRDMDConfig) -> i32;
}
unsafe extern "C" {
    pub fn PRDMDDraw(handle: PRHandle, dots: *mut u8) -> PRResult;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PRJTAGStatus {
    pub commandComplete: bool_t,
    pub tdi: bool_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PRJTAGStatus"][::std::mem::size_of::<PRJTAGStatus>() - 8usize];
    ["Alignment of PRJTAGStatus"][::std::mem::align_of::<PRJTAGStatus>() - 4usize];
    ["Offset of field: PRJTAGStatus::commandComplete"]
        [::std::mem::offset_of!(PRJTAGStatus, commandComplete) - 0usize];
    ["Offset of field: PRJTAGStatus::tdi"][::std::mem::offset_of!(PRJTAGStatus, tdi) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PRJTAGOutputs {
    pub tckMask: bool_t,
    pub tmsMask: bool_t,
    pub tdoMask: bool_t,
    pub tck: bool_t,
    pub tms: bool_t,
    pub tdo: bool_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PRJTAGOutputs"][::std::mem::size_of::<PRJTAGOutputs>() - 24usize];
    ["Alignment of PRJTAGOutputs"][::std::mem::align_of::<PRJTAGOutputs>() - 4usize];
    ["Offset of field: PRJTAGOutputs::tckMask"]
        [::std::mem::offset_of!(PRJTAGOutputs, tckMask) - 0usize];
    ["Offset of field: PRJTAGOutputs::tmsMask"]
        [::std::mem::offset_of!(PRJTAGOutputs, tmsMask) - 4usize];
    ["Offset of field: PRJTAGOutputs::tdoMask"]
        [::std::mem::offset_of!(PRJTAGOutputs, tdoMask) - 8usize];
    ["Offset of field: PRJTAGOutputs::tck"][::std::mem::offset_of!(PRJTAGOutputs, tck) - 12usize];
    ["Offset of field: PRJTAGOutputs::tms"][::std::mem::offset_of!(PRJTAGOutputs, tms) - 16usize];
    ["Offset of field: PRJTAGOutputs::tdo"][::std::mem::offset_of!(PRJTAGOutputs, tdo) - 20usize];
};
unsafe extern "C" {
    pub fn PRJTAGDriveOutputs(
        handle: PRHandle,
        jtagOutputs: *mut PRJTAGOutputs,
        toggleClk: bool_t,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRJTAGWriteTDOMemory(
        handle: PRHandle,
        tableOffset: u16,
        numWords: u16,
        tdoData: *mut u32,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRJTAGShiftTDOData(
        handle: PRHandle,
        numBits: u16,
        dataBlockComplete: bool_t,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRJTAGReadTDIMemory(
        handle: PRHandle,
        tableOffset: u16,
        numWords: u16,
        tdiData: *mut u32,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRJTAGGetStatus(handle: PRHandle, status: *mut PRJTAGStatus) -> PRResult;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PRLED {
    pub boardAddr: u8,
    pub LEDIndex: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PRLED"][::std::mem::size_of::<PRLED>() - 2usize];
    ["Alignment of PRLED"][::std::mem::align_of::<PRLED>() - 1usize];
    ["Offset of field: PRLED::boardAddr"][::std::mem::offset_of!(PRLED, boardAddr) - 0usize];
    ["Offset of field: PRLED::LEDIndex"][::std::mem::offset_of!(PRLED, LEDIndex) - 1usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PRLEDRGB {
    pub pRedLED: *mut PRLED,
    pub pGreenLED: *mut PRLED,
    pub pBlueLED: *mut PRLED,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PRLEDRGB"][::std::mem::size_of::<PRLEDRGB>() - 24usize];
    ["Alignment of PRLEDRGB"][::std::mem::align_of::<PRLEDRGB>() - 8usize];
    ["Offset of field: PRLEDRGB::pRedLED"][::std::mem::offset_of!(PRLEDRGB, pRedLED) - 0usize];
    ["Offset of field: PRLEDRGB::pGreenLED"][::std::mem::offset_of!(PRLEDRGB, pGreenLED) - 8usize];
    ["Offset of field: PRLEDRGB::pBlueLED"][::std::mem::offset_of!(PRLEDRGB, pBlueLED) - 16usize];
};
unsafe extern "C" {
    pub fn PRLEDColor(handle: PRHandle, pLED: *mut PRLED, color: u8) -> PRResult;
}
unsafe extern "C" {
    pub fn PRLEDFadeColor(handle: PRHandle, pLED: *mut PRLED, fadeColor: u8) -> PRResult;
}
unsafe extern "C" {
    pub fn PRLEDFade(handle: PRHandle, pLED: *mut PRLED, fadeColor: u8, fadeRate: u16) -> PRResult;
}
unsafe extern "C" {
    pub fn PRLEDFadeRate(handle: PRHandle, boardAddr: u8, fadeRate: u16) -> PRResult;
}
unsafe extern "C" {
    pub fn PRLEDRGBColor(handle: PRHandle, pLED: *mut PRLEDRGB, color: u32) -> PRResult;
}
unsafe extern "C" {
    pub fn PRLEDRGBFade(
        handle: PRHandle,
        pLED: *mut PRLEDRGB,
        fadeColor: u32,
        fadeRate: u16,
    ) -> PRResult;
}
unsafe extern "C" {
    pub fn PRLEDRGBFadeColor(handle: PRHandle, pLED: *mut PRLEDRGB, fadeColor: u32) -> PRResult;
}
