use std::process::ExitCode;
use std::fmt::{Result, Write};
use std::fs;
use spin::prelude::*;

static MESSAGES: [&str; 1] = [
    "switch_updated"
];

pub fn main() -> ExitCode {
    let dirs = Dirs::default();
    let conf = match load_config(&dirs) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("{}", e);
            return ExitCode::FAILURE;
        }
    };

    let Some(main_module) = conf.module_name else {
        eprintln!("no module name defined in configuration");
        return ExitCode::FAILURE;
    };

    let mut ids: Vec<String> = Vec::new();

    let add = |ids: &mut Vec<String>, name: String| {
        let name = name.trim().to_owned();
        assert!(!name.is_empty());
        ids.push(name);
    };

    for v in conf.fonts.keys()      { add(&mut ids, v.into()) }
    for v in conf.music.keys()      { add(&mut ids, v.into()) }
    for v in conf.sounds.keys()     { add(&mut ids, v.into()) }
    for v in conf.switches.keys()   { add(&mut ids, v.into()) }
    for v in conf.vars.keys()       { add(&mut ids, v.into()) }
    for v in conf.video.keys()      { add(&mut ids, v.into()) }
    for v in conf.vocals.keys()     { add(&mut ids, v.into()) }
    for v in MESSAGES                  { add(&mut ids, v.into()) }

    for (name, vars) in conf.namespaces {
        add(&mut ids, name);
        for v in vars.keys() {
            add(&mut ids, v.to_string());
        }
    }

    for (name, s) in conf.scripts {
        add(&mut ids, name);
        if let Some(group) = s.group {
            add(&mut ids, group);
        }
    }

    ids.sort();
    ids.dedup();

    let mut lua = String::new();
    if let Err(e) = format_source(&ids, &mut lua) {
        eprintln!("error formatting source: {}", e);
        return ExitCode::FAILURE;
    };

    let id_file = dirs.scripts.join(format!("{}.lua", main_module));
    match fs::write(id_file, &lua) {
        Ok(_) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("unable to write: {}", e);
            ExitCode::FAILURE
        }
    }
}

pub fn format_source(ids: &Vec<String>, f: &mut String) -> Result {
    writeln!(f, "-- Code generated by 'id-gen'; DO NOT EDIT\n")?;
    writeln!(f, "local pub = {{}}\n")?;

    for id in ids {
        writeln!(f, "pub.{} = \"{}\"", id.to_uppercase(), id)?;
    }
    writeln!(f, "\nreturn pub")?;
    Ok(())
}